# Set a plain language title for the site.
title: Designer Sketches Podcast

# Write a short description for the site. This is used for "meta description."
description: Learn from history’s most influential designers

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Avoid GitHub API authentication when building locally.
github: [metadata]